install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages('tm')
install.packages('jiebaR')
install.packages('wordcloud2')
